### ISSUE TITLE
When clicking twice on the Menu button you go back to the menu

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#107]
im unsure whether this is a bug or a missing feature, but due to laziness itd be nice if i could look at a profile of someone and by clicking the "Home" button it takes you back to the top of the homepage, like twitter does

**Comment by DRSchlaubi** [comment]
IG because you never leave the home Tab, clicking home again won't do anything, therefore switching to a different gab and back still Shows the Profile. I am unsure what would be the better behavior here

**Comment by ChillLP** [comment]
Well, Sometimes i Look at checkins of Others using the "unterwegs" tab, and IT opens their Profile in the Home Tab, which is quite anoying

**Comment by DRSchlaubi** [comment]
Ok that's not intended

**Comment by jheubuch** [comment]
Already fixed by navigation reimplementation in #171
