### ISSUE TITLE
Forbidden statuses load infinetly

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#117]
Steps to reproduce:
Search for a status that is invisible to you, e.g. because it has been posted for followers only and you are not following the author. When opening the link to the status in the browser, Träwelling shows a " 403 - Status invisible to you.". When opening the same status with Träweldroid, one is presented with the "loading screen" (empty map, empty train information etc.) and it stays that way. I would expect Träwelldroid to display an error message so that I know its not my network connection that causes the problem and I can stop waiting for the status to load sometime. If https://github.com/Traewelling/traewelling/issues/1358 is implemented, Träwelldroid could also show the user profile/a follow button directly after encountering the error.

**Comment by jheubuch** [comment]
From the next release there will be displayed an error if the status cannot be displayed
![Screenshot_20230222_124955](https://user-images.githubusercontent.com/60344409/220612210-a6194028-986c-4eb6-a043-64fa09610ab4.png)
