### ISSUE TITLE
Link to bahn.expert on status detail page

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#120]
After checking in into a train myself or after viewing a checkin of another person that I want to pick up at a station, I often want to check the trains stops and current expected arrival time which is more accurate and up to date on bahn.expert. Currently, I need to paste the train number in bahn.expert or find the train from the departure board. It would be very handy to have a button on the status detail page that takes me to the journey of the train on bahn.expert

**Comment by DRSchlaubi** [comment]
Sadly bahn.expert doesn't accept hafas journey IDs anymore so this will be tricky

**Comment by jheubuch** [comment]
Can be done when Traewelling/traewelling#1704 is merged
