### ISSUE TITLE
Display train number on status detail page

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#121]
As Träwelling is displaying the train number next to the line number for checkins, it would be great to have that information available in Träwelldroid as well. As space is rare, I would be okay with just displaying it on the status detail page.

**Comment by DRSchlaubi** [comment]
Currently the API missed this feature

**Comment by jeriox** [comment]
Do you want to open an issue with träwelling about this or should I do so?

**Comment by DRSchlaubi** [comment]
Feel free to open an issue, but afaik they're already aware of it

**Comment by jheubuch** [comment]
Can be done when Traewelling/traewelling#1704 is merged
