### ISSUE TITLE
Follow button on forbidden status view

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#135]
When encountering a forbidden status, there is a text informing the user about the problem as of #117. Since https://github.com/Traewelling/traewelling/issues/1358, the website directly offers a button to access the author's profile where one can follow the author to be able to view the status afterwards. It would be nice if Traewelldroid offered a similar functionality (button to open the profile or follow the user) on the forbidden view

**Comment by jheubuch** [comment]
Since the username or anything else specific is not delivered by API this is not possible at the moment.

![image](https://github.com/Traewelldroid/traewelldroid/assets/60344409/d4a098ac-5703-48a2-97ab-7afbb057727d)
