### ISSUE TITLE
App crashes on Station entering

### ISSUE THREAD

**Issue by OddSobriquet** [jheubuch/traewelling-android#141]
**Describe the bug**
After entering a station and hitting 'Enter' the app consistently crashes

**To Reproduce**
1. Type Station name
2. Do not select from suggested dropdown list!
3. Hit enter

1. Use location button.

**Expected behavior**
As in the previous version expected behaviour is to display departures of entered station

**Screenshots**
https://github.com/Traewelldroid/traewelldroid/assets/72888738/86ea97a1-ee65-4f57-8593-ffe97819fae6

**Smartphone (please complete the following information):**
 - Device: Redmi9A
 - OS: Android 10 (QP1A.190711.020
 - App-Version: 1.11.1 (83)

**Additional context**
Only appeared after last update that fixed stats page. Cannot select station from suggested dropdown, as the desired station is not being displayed, despite entering the exact station name.

Catlog ![traewelling_crash_filtered.txt](https://github.com/Traewelldroid/traewelldroid/files/11451535/traewelling_crash_filtered.txt)

**Comment by jheubuch** [comment]
Hi! Thanks for reporting this issue!
Sadly there is currently no easy way to fix this on a nice way because I'm in the middle of the migration to a completely new UI framework, on which something like that should not happen again.

I'll try a "quick-and-dirty" fix and release it within the next version (should be available this afternoon).

**Comment by jheubuch** [comment]
The new release is now reviewed by Google. I can either tell you when it's ready to download or if you want to test it asap, you can also download the APK from here: https://github.com/Traewelldroid/traewelldroid/releases/download/v1.12.0/de.hbch.traewelling.apk

**Comment by jheubuch** [comment]
Ok I see it isn't resolved

**Comment by jheubuch** [comment]
Now it should be finally resolved. 😮‍💨
Tell me if it's not!

**Comment by OddSobriquet** [comment]
Manual input seems to be working now, indeed. Locate button still reliably crashes the app.

As long as the manual entering works though, I'm happy 😁
