### ISSUE TITLE
Status detail shows edit button for status of other user

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#169]
When opening a status via a traewlling.de-Link in the app, the new status detail page shows the edit button in the upper right corner instead of the "clone checkin" button. When pressing it, nothing happens. When opening the status detail page by tapping a status in the app, everything works correctly

**Comment by jheubuch** [comment]
May be fixed in the next release due to navigation restructuring. Please test it again then. Thanks.
