### ISSUE TITLE
User profile cannot be visited from status detail page

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#170]
Not sure if a bug or just not yet implemented, feel free to change accordingly.

When viewing the status detail of another user, I can tap the username in the checkin card and I get a visual feedback that this indeed something that I can tap, but nothing happens. I expect the user profile view to open in the same way it does when tapping a username in a checkin card in the overview

**Comment by jheubuch** [comment]
This is expected behavior as to prevent indefinite navigations graphs and them causing errors. Maybe I'll think about removing the ripple animation.
