### ISSUE TITLE
App crashes on loading "Your Check-In has not been shared to Mastodon" notification

### ISSUE THREAD

**Issue by C1710** [jheubuch/traewelling-android#187]
**Describe the bug**
When I try to open notifications using the bottom toolbar, the app crashes.
I have error notifications.

**To Reproduce**
1. Break Träwelling such that it issues an error notification (e.g., by breaking your Fediverse instance where it crossposts to).
2. Open the app.
3. Tap on the notification button on the toolbar.
4. The app crashes.

**Expected behavior**
The notification screen should open

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android 11 with MIUI 12
 - Version: 1.19.0 (100)

**Additional context**
I'll try to find log files later 😅
Given that noone else opened the issue, it might be rather specific to my device; it might even not be caused by Träwelldroid.

The very likely cause for this issue is that `Notification` does not have a type for error notifications, which will at least cause a NullPointerException when trying to get an icon in the UI component.

Solution: Create an Error `NotificationType` and (to prevent similar issues) a generic one.

**Comment by C1710** [comment]
Update: I tried to open it alongside ConnectBot (to use logcat) and weirdly the screen opened while open in split screen.

[EDIT] now that I tried scrolling down a bit, it seems like the crash is caused by a specific notification.

**Comment by C1710** [comment]
My theory: I had some notifications that my Träwelling-check-ins could not be (cross-)posted to Mastodon. When scrolling down so far such that one of these notifications is loaded, it crashes.

**Comment by jheubuch** [comment]
Ouch. Are you able to provide the Response JSON from the notification request (I think just the breaking notification is needed)

That would be very helpful

**Comment by C1710** [comment]
```json
{
  "id": "...",
  "type": "MastodonNotSent",
  "leadFormatted": "Your Check-in has not been shared to Mastodon.",
  "lead": "Your Check-in has not been shared to Mastodon.",
  "noticeFormatted": "notifications.socialNotShared.mastodon.502",
  "notice": "notifications.socialNotShared.mastodon.502",
  "link": "https://traewelling.de/status/...",
  "data": {
    "httpResponseCode": 502,
    "status": {
      "id": 1096695
    }
  },
  "readAt": "2023-06-...",
  "createdAt": "2023-06-...",
  "createdAtForHumans": "1 month ago"
}
```
