### ISSUE TITLE
Can Exit train before Boarding train

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#189]
After checking into the S12 at Köln Steinstr to Köln Messe, i realised i wanted to Go to Köln Hbf instead, so i changed my Exit Point, but i could choose Stations even before Köln Steinstr![Screenshot_20230725_142731_Trwelldroid.jpg](https://github.com/Traewelldroid/traewelldroid/assets/105374102/d8c249e0-7531-4c94-9ed4-5d77ae329022)
![Screenshot_20230725_142738_Trwelldroid.jpg](https://github.com/Traewelldroid/traewelldroid/assets/105374102/baea5eb7-8891-455d-bc69-d2c8b3bcea0e)

(Doesnt Work in träwelling Website)

**Comment by ChillLP** [comment]
It lets me choose Siegburg/Bonn for.example, but Not save that change

**Comment by jheubuch** [comment]
Thanks for reporting! I encountered it by myself a few times but was just too lazy to create an issue 😂

**Comment by ChillLP** [comment]
Wonderful
