### ISSUE TITLE
Enable tags for statuses

### ISSUE THREAD

**Issue by jheubuch** [jheubuch/traewelling-android#213]
As a user I want to tag my journeys with various tags.

Examples are given in the Träwelling docs: https://traewelling.de/api/documentation#/Status/createSingleStatusTag

Maybe for the "default" tags an icon could be provided

**Comment by MrKrisKrisu** [comment]
There are currently only a few recommendations in the Trwl Docs. If you (or someone else) have more general ideas that can be used in multiple applications, let us know and we will add them :)

```
trwl:seat (i.e. 61)
trwl:wagon (i.e. 25)
trwl:ticket (i.e. BahnCard 100 first))
trwl:travel_class (i.e. 1, 2, business, economy, ...)
trwl:locomotive_class (BR424, BR450)
trwl:wagon_class (i.e. Bpmz)
```
