### ISSUE TITLE
[Auth] App crashes on Login with Firefox as only available browser

### ISSUE THREAD

**Issue by echtnurich** [jheubuch/traewelling-android#249]
**Describe the bug**
As of right now, Firefox for Android is blocklisted due to issues with callback during auth.
If there is no other Browser installed, the App will crash 

**To Reproduce**
1. Install Firefox for Android
2. Removed/Deactivate all other Browsers
3. Try to authenticate with a Check-in provider

**Expected behavior**
It Just works.

Proposed solutions:
1. Do not Blocklist Browsers outright
2. Prompt the User to Use blocklisted (greylisted?) Browsers, explaining there might be issues.

**Smartphone:**
 - Device: Fairphone 3
 - OS: Android 11
 - Browser Firefox

**Comment by jheubuch** [comment]
I think this could be done by fixing the OAuth Callback URL to a custom scheme, not `https`.

Additionally the `ActivityNotFoundException` should be caught.

https://sentry.traewelldroid.de/organizations/traewelldroid/issues/162/events/8a7e3574303a411ab15ab4f32c3ec287/

**Comment by jheubuch** [comment]
Just need to re-open that open 🥴

**Comment by echtnurich** [comment]
Just to bump this, multiple people told me that they would use the App, if only they could log in without installing another browser.

It would really be nice to have a way to still use FF, forfeiting all rights to complain about FF-related bugs of course. ;)

**Comment by jheubuch** [comment]
Yeah, sure, that's why I reopened the issue 🥴

**Comment by rugk** [comment]
Oh uff, I know for other apps this workflow works/worked. Is there already a bug report at Mozilla for this? Or don't they do anything wrong and your app should not crash uhm…

**Comment by jheubuch** [comment]
I added an HTTP redirect rule to my webserver which redirects to my app custom theme when accessing via Browser. This results in automatically opening Träwelldroid after authenticating
