### ISSUE TITLE
Show unique Train identifier in search

### ISSUE THREAD

**Issue by echtnurich** [jheubuch/traewelling-android#254]
Ich konnte gerade den Zug mit +65 und den Zug mit +5 kaum auseinanderhalten.
Wäre es möglich zB Verspätung, ursprüngliche Abfahrt oder Zugnummer anzuzeigen?

Auf dem Screenshot ist es wieder eindeutiger, aber nur an der Farbe zu unterscheiden ist wahrscheinlich auch nicht sehr barrierefrei.
![IMG_20230909_195129_858](https://github.com/Traewelldroid/traewelldroid/assets/24839517/afd3c00e-e4cc-4873-8809-a46baf4b26ac)

**Comment by jheubuch** [comment]
Ist möglich. :)
Danke für die Idee!
