### ISSUE TITLE
Order cards by actual time, not planned time

### ISSUE THREAD

**Issue by echtnurich** [jheubuch/traewelling-android#255]
Meine Fahrten sind aktuell krumm sortiert, weil mein Anschlusszug +70 hatte, wäre das möglich die an der tatsächlichen Zeit zu sortieren, solange die auch verfügbar ist?

![IMG_20230909_195136_086](https://github.com/Traewelldroid/traewelldroid/assets/24839517/e90e5172-4f03-4b2a-a0c4-0da063c5d98b)

**Comment by echtnurich** [comment]
This might be linked to traewelling/traewelling#1382

**Comment by jheubuch** [comment]
Yep, mabye I'd see that on API side
(For endless scrolling, it could have weird side effects if sorting is done on client side...)
