### ISSUE TITLE
Add "Train Nickname" Tag

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#256]
A Tag to add the name of the Train/loco rather than the Baureihe would be nice, as i classify my trains by BR, and Sometimes i would Like to add the Taufnamen

**Comment by jheubuch** [comment]
I'd like to clarify this with the @Traewelling team, until documented, I'll keep this as blocked.

**Comment by ChillLP** [comment]
Ref: https://github.com/Traewelling/traewelling/discussions/2067

**Comment by MrKrisKrisu** [comment]
> I'd like to clarify this with the @Traewelling team, until documented, I'll keep this as blocked.

Status tags are not required to have documented `trwl:__` value. You can use your own tags with your prefix as well.

**Comment by jheubuch** [comment]
> > I'd like to clarify this with the @Traewelling team, until documented, I'll keep this as blocked.
> 
> Status tags are not required to have documented `trwl:__` value. You can use your own tags with your prefix as well.

Yes I know, but for interoperability reasons, I think it would be best if everywhere it's the same :D

**Comment by jheubuch** [comment]
Implemented with `trwl:vehicle_number`
