### ISSUE TITLE
Request connection data from HAFAS/DBRest directly

### ISSUE THREAD

**Issue by jheubuch** [jheubuch/traewelling-android#26]
For a better performance it could be useful to request connection details directly from the HAFAS or a DB Rest instance

**Comment by jheubuch** [comment]
Alternatively, the REST API by bahn.expert could be used.
https://docs.bahn.expert/
OpenAPI: https://docs.bahn.expert/swagger.json

**Comment by DRSchlaubi** [comment]
The bahn.expert API is now private, therefore we can no longer use that
as for db rest, are there any HAFAS endpoints we would currently need?
