### ISSUE TITLE
Unable to login due to non-existent permission

### ISSUE THREAD

**Issue by Der-Flip** [jheubuch/traewelling-android#270]
**Describe the bug**
I am unable to login as the app requests permission to open links. I cannot grant this permission because it doesn't exist.

**To Reproduce**
1. Open app
2. Attempt to log in

**Expected behavior**
Link opens in browser or in-app / login possible

**Screenshots**
![Screenshot_2023-09-27-10-51-47-691_com.google.android.permissioncontroller.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/2b45f093-01f3-4da2-b750-c9c7ab81afe3)

![Screenshot_2023-09-27-10-51-34-209_de.hbch.traewelling.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/2cf5931f-747e-4df5-b39a-46eb50c92a8f)

![Screenshot_2023-09-27-10-51-52-911_com.miui.securitycenter.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/0746c473-6f63-4a4d-a805-a5a4d1b1f753)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi9C 
 - OS: Android 10 QP1A.190711.020
 - Browser: Firefox 117.1.0
 - Version: Träwelldroid 1.20.1

**Additional context**
I wasnt able to open the app due to sickness for about 3 weeks to a month. Today when opening the app I was logged out. I still was (and am) logged in in Firefox.

**Comment by oneiricbotcelot** [comment]
Hi, 

just an unqualified comment:

I appended a few screenshots from my device on Android 13 on how I can get into the corresponding setting to adjust "open supported links". I hope this helps.

![Screenshot_20230927-110552](https://github.com/Traewelldroid/traewelldroid/assets/33320318/99115b7e-2018-49f1-ba74-f91d02d83bba)
![Screenshot_20230927-110602](https://github.com/Traewelldroid/traewelldroid/assets/33320318/cecb7109-f55d-4485-b802-639decd0dd4f)
![Screenshot_20230927-110611](https://github.com/Traewelldroid/traewelldroid/assets/33320318/67855c05-7cdd-48e4-8a3f-e39a948e00cb)
![Screenshot_20230927-110619](https://github.com/Traewelldroid/traewelldroid/assets/33320318/e4d5068f-9227-4ed7-8160-87d46ed47f4f)
![Screenshot_20230927-110627](https://github.com/Traewelldroid/traewelldroid/assets/33320318/32e7b002-5e12-4ff3-9247-e50063f68966)

**Comment by Der-Flip** [comment]
Afaik Android 10 doesn't have that

![Screenshot_2023-09-27-11-21-31-097_com.android.settings.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/c78499d5-6f05-489f-89bb-f24236acc5cf)

![Screenshot_2023-09-27-11-20-48-928_com.android.settings.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/aa5a3508-eb5d-4ead-bc34-729f5111c481)

![Screenshot_2023-09-27-11-21-17-169_com.android.settings.jpg](https://github.com/Traewelldroid/traewelldroid/assets/18213041/0dec8993-bc66-43fd-8143-343c6e1761df)


Apps > permissions just leads to the permission option sent in my initial screenshots.

**Comment by jheubuch** [comment]
Android 10 does also have that, but I guess you'll find it at "Default apps" -> Träwelldroid.

**Comment by Der-Flip** [comment]
Okay, I found it, it's extremely hidden....

~~But it is empty, nothing to grant here...~~

Nevermind it just takes ages to load ...

**Comment by Der-Flip** [comment]
Okay, my bad... it works now, thanks for the help...
In case someone stumbles upon this:

Settings > Apps > Manage Apps > 3-dots-menu top right > default apps > opening links > just wait

**Comment by jheubuch** [comment]
Since nothing is done here...
