### ISSUE TITLE
Zeitangaben komisch formatiert

### ISSUE THREAD

**Issue by do-m-inik** [jheubuch/traewelling-android#272]
![Screenshot_20231023_102459_Trwelldroid.jpg](https://github.com/Traewelldroid/traewelldroid/assets/94101596/cd676ab9-9dbe-4d12-a21e-28fe1d711d0e)

Was der Fehler ist sollte am Screenshot glaube ich erkennbar sein. Die Zeitangaben sehen überall so aus.

Handy: Samsung Galaxy S10e
Android: 12

App Version: v2.1.6

**Comment by jheubuch** [comment]
Cannot be reproduced and no other reports of this behaviour.
