### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by marlonbasten** [jheubuch/traewelling-android#297]
**Describe the bug**
When clicking "Login with Träwelling" I get a 500 error.

**To Reproduce**
1. Download the app
2. Click on 'Login with Träwelling'
3. See error

**Expected behavior**
The ability to login.

**Screenshots**
![Screenshot_2023-11-14-15-57-36-61_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Traewelldroid/traewelldroid/assets/31259698/20bdd54a-7d10-40b3-bc45-022a02de8eaf)

**Smartphone (please complete the following information):**
 - Device: Oppo Find X5 Pro
 - OS: Android 13
 - Browser Chrome
 - Version 2.3.2-play

**Comment by MrKrisKrisu** [comment]
This is currently a bug on the side of traewelling itself. You have entered wrong credentials and instead of a human readable message you see a error 500. Sorry.

**Comment by jheubuch** [comment]
@MrKrisKrisu thanks for the explanation.
I'm closing this then since there is nothing to do from Träwelldroid-side.
