### ISSUE TITLE
App returns to login screen after logging in

### ISSUE THREAD

**Issue by klukas144** [jheubuch/traewelling-android#306]
I click on login with traewelling, then accept that träwelldroid may have access to all the data. The app shows the home screen for about 1 second and then returns to the login screen.
I expect the app to stay on the home screen after the login.

 - Device: Pixel 6a
 - OS: Android 14
 - Browser: Chrome
 - Version: 2.4.0-play

**Comment by jheubuch** [comment]
already fixed via #305 and #307
