### ISSUE TITLE
Träwelldroid does not show notifications regarding errors with Mastodon

### ISSUE THREAD

**Issue by Paktosan** [jheubuch/traewelling-android#313]
First of all: Thanks for this great app and happy Christmas!

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a linked Mastodon account
2. Deauthorize Traewelling
3. Try to post a journey to Mastodon

**Expected behaviour**
Being able to see the error notification.

**Screenshots**
![photo_2023-12-24_10-03-39](https://github.com/Traewelldroid/traewelldroid/assets/4009269/0b7e708b-21eb-4300-8a3d-195ac1543eee)
![Screenshot_20231224_100823](https://github.com/Traewelldroid/traewelldroid/assets/4009269/b45cdc1a-1c43-4350-9fa3-3a5c85400e36)

**Smartphone (please complete the following information):**
 - Device: Nokia X10
 - OS: Android 13
 - App Version: v2.4.2-play (137)

**Comment by jheubuch** [comment]
Okay this an error with @Traewelling (Mastodon URL should be deleted after unlinking). When this is working correctly you shouldn't be able to post to Mastodon anymore.
But I think I will also implement that those texts are being displayed.

See: https://github.com/Traewelling/traewelling/issues/2256
