### ISSUE TITLE
Check-Ins change their assigned dates

### ISSUE THREAD

**Issue by klukas144** [jheubuch/traewelling-android#332]
Some check-ins change the date depending if they're shown in the feed/profile or in the own daily summary

Steps to reproduce: check in to a journey that has started on the previous day (I suppose this is the way to do so)

If you look at the screenshot, the check-in has been made on the 14th, but in the daily summary of the 14th there is no check-in, it is indeed shown as part of the summary of the 13th. My guess is that because the tram started its journey on the 13th the check-in is assigned to the daily summary of the 13th.

Issues happened on Pixel 6a, below are screenshots of an example

![Screenshot_20240314-181050](https://github.com/Traewelldroid/traewelldroid/assets/152178212/ffdf151f-ad8c-4b80-b011-206ac4297f24)
![Screenshot_20240314-181036](https://github.com/Traewelldroid/traewelldroid/assets/152178212/8bae69ca-27b0-4a21-806d-ea81648bb7c2)

**Comment by jheubuch** [comment]
Hi!
Thanks for your report. I guess this is an issue with the Träwelling interface.
I'll investigate further and open an issue on their side if needed.

**Comment by jheubuch** [comment]
Since this is an issue on Träwelling API, I created an issue there and closing this now.

https://github.com/Traewelling/traewelling/issues/2488
