### ISSUE TITLE
Open login page in default browser (custom tab) instead of Chrome/ium always

### ISSUE THREAD

**Issue by rugk** [jheubuch/traewelling-android#333]
**Is your feature request related to a problem? Please describe.**
I am usually logged-in in traewelling in my default browser. It seems you currently, however, somehow force Chrome (or in my case Chromium, as it is the only one installed) to be used here. Also you seem to be using custom tabs, which is fine (IMHO).

So the first screen I see is a browser where I need to login, which I don't use. (Firefox is set as my default browser.) 

I mean you _have a button to open it in your default browser there_ just the login does not work then (it just shows the home page, likely the OAUTH token is already lost, due to the first redirect to the login page):
![Screenshot_20240315-095607_1](https://github.com/Traewelldroid/traewelldroid/assets/11966684/41986381-e6b3-4a6b-9b8d-2e723370d0fc)

**Describe the solution you'd like**
Firefox for Android e.g. supports custom tabs, too. I am not too deep into Android development, but I guess you should be able to choose/allow this too/just default on the default browser. https://wiki.mozilla.org/Mobile/Firefox_for_Android/custom_Tab

**Describe alternatives you've considered**
* don't use custom tabs, but open in default browser always. This is also way simpler and also uses the default browser. [AFAIK this is how StreetComplete does it until today](https://github.com/streetcomplete/StreetComplete/issues/906).

**Additional context**
The UX impact is just without this, this complicates the initial workflow/setup for anyone not using Chrome/ium actively.

**Comment by jheubuch** [comment]
relates to #249
