### ISSUE TITLE
Incorrect location for station Erfurt Hbf

### ISSUE THREAD

**Issue by MartinLangbecker** [jheubuch/traewelling-android#341]
**Description**
When checking in any connection to or from Erfurt Hbf, the wrong coordinates are used for the station. This leads to wrong distance calculations as well as erratic and inconsistent lines on the map.

**Reproduction Steps**
1. Check in any connection to or from Erfurt, e. g. Ilmenau - > Erfurt.
2. Open the detail view of the checked in connect.
3. Verify on the map that the line does not end in Erfurt Hbf.
4. Verify that the calculated distance is 47 km (should be 51 km).

**Expected behavior**
The correct location of the station should be used so that distance calculation and map display match the actual connection.

**Screenshots**
![IMG_20240401_153411](https://github.com/Traewelldroid/traewelldroid/assets/74348656/21e2885d-a227-4f54-b538-3a52a28dd961)
![IMG_20240401_153653](https://github.com/Traewelldroid/traewelldroid/assets/74348656/2e13b2b0-8243-4ebf-bafb-8bc971196d6c) 

**Smartphone**
 - Device: Fairphone 4
 - OS: Android 13
 - App Version: v2.7.1-play (142)

**Comment by jheubuch** [comment]
Hi,
this doesn't seem like a problem with Träwelldroid.

It's either an API problem on @Traewelling side or a data problem from Deutsche Bahn data,

I'll let the @Traewelling team have a look.

**Comment by flecken66** [comment]
This is due to incorrect data from DB. Bahn.experte has the same issue.

![Screenshot_20240402-094249.png](https://github.com/Traewelldroid/traewelldroid/assets/32737713/0ec0ef04-fabd-4510-9ceb-e28b500d6adb)

**Comment by jheubuch** [comment]
Thanks for your input @flecken66 

Closing this due to errorneous data then.
