### ISSUE TITLE
Travelyx checkin do not apply same visibility setting

### ISSUE THREAD

**Issue by rugk** [jheubuch/traewelling-android#347]
**Describe the bug**
AFAIK when you checkin to both Traewelling and Travelyx, the "visbility/privacy settings", i.e. whether a checkin is public, follower-only, etc. is not applied to Travelyx.

**To Reproduce**
1. Setup both checkin services.
2. Select "follower-only" in checkin dialog.
3. Checkin.

Only on Traewelling it is set to follower-only then… 

**Expected behavior**
For privacy/security/[POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) reasons, it should keep the same visibility in all network services. Otherwise private information can of course be exposed.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
Device: Fairphone 4 (FP4)  
OS: Android 14, CalyxOS 5.5.2. 
source: F-Droid  
version: v. 2.7.1  
Build-ID: `AP1A.240305.019.A1.24505020`

**Additional context**
N/A

**Comment by jheubuch** [comment]
According to the API docs, there is no possibility to send some visibility (at least i don't see it?).

https://travelynx.de/api

**Comment by rugk** [comment]
The big JSON at least lists it:
```json
"visibility" : {
"desc": "private" / "unlisted" / "followers" / "travelynx" / "public",
"level": 10 / 30 / 60 / 80 / 100
}
```

But that may be readonly hmm? 

So opened an issue for that: https://github.com/derf/travelynx/issues/135

(BTW, you may add/use a tag "blocked" for such issues, depending on outside factors.)
