### ISSUE TITLE
404 after pressing Autorisieren 

### ISSUE THREAD

**Issue by dogo77** [jheubuch/traewelling-android#348]
**Describe the bug**
Got a new Phone and tried to reactivate Träwelldroid 2.7.2
I see the wellcome screen with the link to »mit  träwelling anmelden«
click it
see the consent website
click on the green »autorisieren« button
and get a 404 not found website by nginx 1.18.0

**Expected behavior**
be logged in to the app

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 13 Pro 4G]
 - OS: [Android/Miui]
 - Version [14]

**Additional context**
deleted the old token under 
[https://traewelling.de/settings/security/api-tokens](url)

**Comment by jheubuch** [comment]
Please use the "Open in app" functionality of your browser after the authorization page (on the Not Found page) to redirect the auth response to Träwelldroid. Some mobile browsers (i.e. Firefox) aren't opening apps on corresponding links by default.

Yes, the 404 page is not the most elegant solution but the "mainstream" user does not occur this. But I'll have a look on creating a page explaining what to do, when the auth response is not redirected to Träwelldroid.

**Comment by dogo77** [comment]
Ah, that worked, thank you.
