### ISSUE TITLE
Add distance statistics

### ISSUE THREAD

**Issue by klukas144** [jheubuch/traewelling-android#357]
It would be cool to also have a tab for distance (Strecke) in the statistics, preferably at the red-colored free space

![Screenshot_20240523-204736](https://github.com/Traewelldroid/traewelldroid/assets/152178212/24c35ce3-26d8-4c8f-b2f3-92499a18166b)

**Comment by jheubuch** [comment]
Hi,

thanks for your suggestion.

Currently the Träwelling API (the interface where I get those data from) isn't returning the distance statistics. If available, of course I would have added them to those views.

Thanks for your understanding.
