### ISSUE TITLE
line icons not showing correctly (several networks, maybe my own error)

### ISSUE THREAD

**Issue by ghost** [jheubuch/traewelling-android#358]
**Describe the bug**
line colours aren't showing up correctly on the networks
- prague
- dessau (DWE trains)
- bremen

**To Reproduce**
Enter "Praha hl.n.", "Bremen Hbf" or "Dessau-Roßlau" to see the missing icons.

**Expected behavior**
Correct line icons as provided in the [line-colors.csv](https://github.com/Traewelling/line-colors/blob/main/line-colors.csv) file.

**Screenshots**
![image](https://github.com/Traewelldroid/traewelldroid/assets/160403915/77e36b53-3356-4e9f-8f8b-6a57d0ee7e4f)
Träwelldroid with newest line icons.

**Smartphone (please complete the following information):**
 - Device: T Mobile T Phone Pro
 - OS: Android 13
 
**Additional context**

(originally posted at Traewelling)
https://github.com/Traewelling/line-colors/issues/153

**on a personal note**
did i miss something while adding those line colours? it all seems correct to me, so i'm assuming, it's an issue with Träwelldroid.

**Comment by jheubuch** [comment]
I just commented on the other issue - please come back after the changes to the CSV have been made and the errors with Träwelldroid still occur.
