### ISSUE TITLE
Line icons not showing up

### ISSUE THREAD

**Issue by ET430-Rosenheim** [jheubuch/traewelling-android#361]
**Describe the bug**
The colored icons are no longer showing up since yesterday for many operators like DB Regio Bayern, BRB and Go-Ahead Bayern. I don't know if there's anything to do with the Fahrplanwechsel yesterday

**To Reproduce**
1. Go to 'Augsburg Hbf'
2. Scroll down to the list of trains
3. See error

**Expected behavior**
Line icons should be shown instead of pure text

**Screenshots**

![Screenshot_20240610-201757](https://github.com/Traewelldroid/traewelldroid/assets/92975211/773b1245-4cc0-4278-942e-78b7862434a2)

**Smartphone (please complete the following information):**
 - Device: Sony XQ-AT52
 - OS: Android 12
 - Version v2.7.5-play (147)

**Additional context**
Ironically, all check-ins before the Fahrplanwechsel showed up normally as icons when there are, and an icon mysteriously appears for the Ersatz-RE7 (39548)

**Comment by jheubuch** [comment]
Hi,

since there were changes on the DB HAFAS system, several line IDs changed from the summer timetable change.

There is nothing we can do about that - the entries for the line icons need to be updated in the CSV.
