### ISSUE TITLE
Unable to add tags

### ISSUE THREAD

**Issue by ET430-Rosenheim** [jheubuch/traewelling-android#364]
**Describe the bug**
Unable to add tags in app after update

**To Reproduce**
1. Check into any train
2. See error: No option to add tags

**Expected behavior**
Shouöd have been able to add tags as in previous versions

**Screenshots**
![Screenshot_20240620-093710](https://github.com/Traewelldroid/traewelldroid/assets/92975211/7a075c8b-dc44-4f74-8a58-f7636acccb48)
![Screenshot_20240620-093719](https://github.com/Traewelldroid/traewelldroid/assets/92975211/84a07afb-bfdd-4a35-b107-ec1c9e422f82)

**Smartphone (please complete the following information):**
 - Device: Sony XQ-AT52
 - OS: Android 12
 - Version v2.8.0-play (148)

**Comment by jheubuch** [comment]
Already fixed in #363 - rollout is already running.
