### ISSUE TITLE
Date picker cut off

### ISSUE THREAD

**Issue by iw0nderhow** [jheubuch/traewelling-android#367]
**Describe the bug**
Sunday is missing from the check-in date picker. The date picker in the edit screen shows Sunday.

**To Reproduce**
1. Go to the check in dialogue 
2. Click on the date picker

**Expected behavior**
I can see Sunday

**Screenshots**
![Screenshot_20240625_083346_Trwelldroid.png](https://github.com/Traewelldroid/traewelldroid/assets/6024426/300cb13d-f90b-492c-bfed-06864b29f4e8)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Android 14
 - Traewelldroid v2.8.2-play

**Comment by jheubuch** [comment]
I actually **can** see Sunday but I think I need to investigate this further...

![Screenshot_20240625-085639.png](https://github.com/Traewelldroid/traewelldroid/assets/60344409/46912fdb-2803-46f6-be8c-2fd45daa3823)

**Comment by flecken66** [comment]
This has to do with the display size of the UI.
Settings > Display > Display Size and Text > Display Size

![Screenshot_20240625-085907.png](https://github.com/Traewelldroid/traewelldroid/assets/32737713/fd36adc2-2f97-4b99-9c3c-066c239278ba)

**Comment by tintinmaster** [comment]
Got the same problem
