### ISSUE TITLE
Cant edit Checkins

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#386]
For about two weeks or so i couldnt change my Exit Station or my Checkintext after cheking in.

**To Reproduce**
Check into train
try and edit status
Sometimes actually edits it but will load to infinity
Störung.

**Expected behavior**
Actual Changes in Status

Smartphone 
Device: Samsung Galaxy S22+
OS: Android 14
Version [newest]

**Comment by jheubuch** [comment]
I tried it several times on my phone now, but I cannot reproduce it. Are you sure that you are using the latest version?

**Comment by ChillLP** [comment]
Nope, seems to have gotten fixed, my bad
