### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by amogus07** [jheubuch/traewelling-android#392]
**Describe the bug**
The app keeps prompting me to enable it can open links, even though I already did that. 

**To Reproduce**
1. Install Träwelldroid from F-Droid or the Play Store
2. Open the app
3. Press "Login with Träwelling"
4. Press "Yes"
5. Add "traewelling.de" to the list of supported links
6. Go back
7. Press "Login with Träwelling"
8. The prompt appears again! 

**Expected behavior**
*Login page opens*

**Screenshots**
![Screenshot_20240723-084519_Träwelldroid](https://github.com/user-attachments/assets/4321b406-f4e4-4ec0-b1bb-4e732644d688)
![Screenshot_20240723-084523_Settings](https://github.com/user-attachments/assets/bf63df97-9499-4356-aafa-bf021b9b0373)

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: awakenos 3.9 ⁄ Android 13
 - Version 33

**Comment by jheubuch** [comment]
Woohoo, another Android manufacturer which does stuff that is not compliant with common Android...

**Comment by jheubuch** [comment]
This should be fixed by the next release.
