### ISSUE TITLE
No notifications no matter what

### ISSUE THREAD

**Issue by mine-ing** [jheubuch/traewelling-android#393]
**Describe the bug**
An Android system notification should show up whenever someone likes a check-in, is riding along, follows you...

**To Reproduce**
Receive a notification 

**Expected behavior**
Get a notification 

**Screenshots**

Notifications tab:
![Screenshot_20240723-101642_1](https://github.com/user-attachments/assets/8fbb607f-6dfd-4177-a950-984c7f1736ca)

System notifications:
![Screenshot_20240723-101604_1](https://github.com/user-attachments/assets/c3dee976-c2ad-4222-9e9e-93a04462196f)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8, Asus Zenfone 8
 - OS: Android
 - Version 12, 13 and 14

**Additional context**
I appear to not be the only one as one of my friends with a conpletely different Android phone is having the same issue

**Comment by jheubuch** [comment]
Hi, please try to logout and login again.

**Comment by mine-ing** [comment]
Hi, that seems to have fixed the issue, but I feel like I shouldn't have to login twice for notifications to work
