### ISSUE TITLE
Place Operator more prominently

### ISSUE THREAD

**Issue by kpleiss** [jheubuch/traewelling-android#406]
To see the operator you have to open the check in and scroll to the end. That's not really intuitive. I think it would be better to display the operator in the check in overview. Perhaps below line number and distance?

**Comment by jheubuch** [comment]
More text information like the operator would overload the CheckIn-Card. Also the operator is not available for all statuses. This causes a different look for each status and would destroy the continuous look of the cards. Therefore I wouldn't implement this for now.
