### ISSUE TITLE
can't accept follow request from within the app

### ISSUE THREAD

**Issue by tastytea** [jheubuch/traewelling-android#408]
**Is your feature request related to a problem? Please describe.**
when i get a follow request, i can't accept it through Träwelldroid, i have to open https://traewelling.de/ for that

**Describe the solution you'd like**
the option to accept/reject follow requests

**Describe alternatives you've considered**
doing it on https://traewelling.de/ works as long as you have access to your password on your android device

**Comment by jheubuch** [comment]
This is already under development and currently blocked by https://github.com/Traewelling/traewelling/pull/2861

When this merge request is approved, I can continue working on this.
