### ISSUE TITLE
Font options

### ISSUE THREAD

**Issue by wolfyjade** [jheubuch/traewelling-android#418]
**Is your feature request related to a problem? Please describe.**

I'm not entirely happy with the choice of fonts in that app, and I'd like to have a bit more consistency with the fonts across the system. (*I'd say this has very low priority though, so while I'd be happy if that setting becomes a thing, it's nothing of priority for me personally.*)

**Describe the solution you'd like**

A toggle in the "Display configuration" settings (or wherever it could fit better) that would allow me to use the font that my phone's system uses, giving me an option to just use the system's font for the UI except for the greeting text (that at this time of the day, 20:52, greets me with "Good evening :)").

**Describe alternatives you've considered**

An alternative option would be to add the font that Träwelling uses (if possible) so that at least those two could use the same fonts. As an alternative to that, it could also be integrated (to still add a toggle to switch to the system font) as an option into some sort of drop-down menu that would allow one to switch between 3 fonts: The system font, the font that's already used by the app and the font that Träwelling is using.

[*removed a section of the template because that doesn't really apply here (at least I think so)*]

**Comment by jheubuch** [comment]
I like the idea of font switching, but I don't know if it would be the best to use "Nunito" (the font Träwelling uses) because the impression could be created that Träwelldroid is a part of Träwelling (which is not the case).

But a toggle between System font and Raleway (the "Träwelldroid font") would be nice imo.
