### ISSUE TITLE
Missing padding on sharing dialogue

### ISSUE THREAD

**Issue by thilobillerbeck** [jheubuch/traewelling-android#422]
**Describe the bug**
When sharing a ride, the opening dialogue is not padded

**To Reproduce**
1. Go to an overview that shows journeys
2. Click on a journey 
3. Open the sharing dialogue via the three dot menu

**Expected behavior**
The dialogue should offer some amount of padding.

**Screenshots**
![Screenshot_20240930-090606.png](https://github.com/user-attachments/assets/cbb65100-ca07-406f-83e4-936b277995aa)

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: Android 
 - Version 14

**Comment by jheubuch** [comment]
Hey there,
thanks for your request.

Could you provide some screenshot for that? Because on my device it has (I think) good padding..

![Screenshot_20240930-223630.png](https://github.com/user-attachments/assets/b7ed8090-5c03-4d06-8107-19153ec8f5c7)

**Comment by jheubuch** [comment]
Okay nevermind, network connection was just too slow to display your screenshot. 😅

Indeed the padding could be increased a bit, that's true. I wonder why I built it like that 🤔
