### ISSUE TITLE
Allow custom APIs

### ISSUE THREAD

**Issue by ACH1980** [jheubuch/traewelling-android#427]
I would like to create my own travel status system, and would love to do that with existing apps rather than new ones.

Provide a button to add custom APIs. I'd suggest that you add a "add custom API" button that when clicked asks if it should follow the travelynx API scheme or the Traewelling one, that way you can just use the existing implementation and I guess it's already kinda good 👍

**Comment by jheubuch** [comment]
Hi, if you want to use a custom API, feel free to fork Träwelldroid and implement your own custom API. Since this is not a common requested feature, I won't implement this (for now).

**Comment by ACH1980** [comment]
Wenn ich das mache, könntest du mir das kompilieren und mir die APK zusenden? Irgendwie war ich bisher zu blöd ein Setup einzurichten bei dem ich Java kompiliert bekomme, muss das Mal machen wenn ich im Hackspace bin (da gibt's Leute die mir helfen können), aber das wird vermutlich nicht zeitnah passieren 🫣

Testen kann ich dann ggf. selbst, nur kompilieren kann ich Stand jetzt nicht selbst 😕
