### ISSUE TITLE
Google Play app has overly strict country restrictions 

### ISSUE THREAD

**Issue by agraven** [jheubuch/traewelling-android#429]
**Describe the bug**
The app cannot be downloaded with your google account location set to Denmark even though registering trips in Denmark works just fine.

**To Reproduce**
Visit the store page with country set to Denmark

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android
 - Version: 12

**Additional context**

**Comment by jheubuch** [comment]
I added Denmark to the allowlist of countries in which the app is available. I'll close the issue when Google has published it there.

**Comment by jheubuch** [comment]
Should be available in the next minutes. ✅
