### ISSUE TITLE
Delete check-in icon and User icon drawn over each other

### ISSUE THREAD

**Issue by pief** [jheubuch/traewelling-android#43]
With long user names the user icon slides that far to the left that it is drawn over the "Delete check-in" icon.

![Screenshot_20220830-105437_Trwelldroid](https://user-images.githubusercontent.com/2843983/187395286-00f0db8d-e038-4e3b-aa6c-44954c31c921.jpg)

**Comment by jheubuch** [comment]
From the next release, the edit/delete button will be reachable via a popup menu:
![options](https://user-images.githubusercontent.com/60344409/220601129-963a3227-ee6d-4cae-81dd-cf705b29b694.png)
