### ISSUE TITLE
Filter for "now traveling"

### ISSUE THREAD

**Issue by ACH1980** [jheubuch/traewelling-android#432]
Problem: 
The list of people traveling is always quite long, but it's pretty much useless for people in northern Germany to see who is traveling in Berlin/Munich/Frankfurt/etc.

Suggestion:
Filters that allow filtering by the following criteria: 
- type of vehicle (Bus, RB, RE, IC/EC, ICE, etc.)
- area (around a certain location (either manually or just last destination), or by region) in which the origin/destination of the other traveler is (optional and maybe harder to realize: also add the enroute stops of the other travelers to the filtering (so that also people only going through that area without changing trains will be shown))

Alternative:
Sort by distance (although it might be best to add this with the filtering all together)

**Comment by jheubuch** [comment]
Closing since there is no API endpoints covering the feature request.
