### ISSUE TITLE
Remove `DependencyInfoBlock`

### ISSUE THREAD

**Issue by licaon-kter** [jheubuch/traewelling-android#434]
Ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8244530261#L540

hmm looks like you have the `DependencyInfoBlock` thing :disappointed: 

Can you add this fix: https://gitlab.com/fdroid/fdroidserver/-/issues/1056#note_1218193185 ?
```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

we'll need a new version, tag, release

**Comment by jheubuch** [comment]
Mhm, I can do that, but how is this happening since it was never a problem before?

**Comment by licaon-kter** [comment]
It was forever, just that we slowly started enforcing it, first for new apps, now for updates.

**Comment by jheubuch** [comment]
Release 2.15.7 is created and published.

**Comment by licaon-kter** [comment]
Thanks
