### ISSUE TITLE
time overwrite fields not visible until scheduled time is reached

### ISSUE THREAD

**Issue by techtoto** [jheubuch/traewelling-android#439]
**Describe the bug**
The fields to overwrite the departure/arrival time are only visible after the scheduled time is reached. Especially on earlier arrivals, this is quite annoying.

**To Reproduce**
1. Edit a check-in where the scheduled arrival and/or departure time is not reached yet

**Expected behavior**
Both overwrite fields should be visible

**Screenshots**
![Screenshot_20241113-140748](https://github.com/user-attachments/assets/ab0a2a0d-84f6-47ad-aef7-df79d1eb26dc)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 14
 - Version: 2.15.6-play

**Comment by jheubuch** [comment]
This is not a bug since I intended this behaviour when developing the feature. I'll keep it open as an enhancement.

**Comment by jheubuch** [comment]
I enabled the overriding of the times from 30mins prior departure/arrival.
