### ISSUE TITLE
Year in review data incorrect

### ISSUE THREAD

**Issue by CHirch** [jheubuch/traewelling-android#456]
**Describe the bug**
The data shown in the Year review does not match the real data. There are less kilometres and the longest journey, slowest journey and most unpunctual are all incorrect as there are more extreme journey in this years dataset.
I cannot recognise a pattern which Check-ins are not included in the statistics calculation.

**Expected behavior**
The data matches the reality

**Smartphone (please complete the following information):**
 - Device: Android 12, Samsung
 - Version V2.17.1-play (178)

Btw, I really like the yearly recap. If only the data would be correct.

**Comment by jheubuch** [comment]
Hi, the data for the year in review comes from @Traewelling. Please consider to file an issue there or text the Träwelling support via the website. Thank you.
