### ISSUE TITLE
Check into the same train twice or thrice

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#461]
### Is there an existing issue for your request?

- [X] I have searched the existing issues and did not find an open one

### Is your issue regarding to timetable or routing data within any check-in displayed in
Träwelldroid?

- [X] I have no issue with the displayed timetable or check-in data.

### Describe the bug / current behaviour

Clicking on a notification that someone liked my own checkin, wanting to delete said check-in, it gave me the options to either report, or join my connection (note, I'm still looking at my own check-in). Clicking said "join" connection button behaves as expected. After forcing the check-in I am now on that train, twice.

![Screenshot_20241220_070552_Trwelldroid](https://github.com/user-attachments/assets/b96d09bb-90e9-40a8-ba87-d1f17a845a0d)
![Screenshot_20241220_070605_Trwelldroid](https://github.com/user-attachments/assets/e1276662-b994-48ff-9693-7b718a95ff18)

### Describe the expected behaviour

Throw an error/ stop me from checking into a connection on the same stations more than once

### Your app version

V2.17.3

**Comment by jheubuch** [comment]
Hi, in my opinion it should be the task of the @Traewelling API to inform me about check in conflicts. Usually conflicts should be detected there. To investigate why those aren't detected, please consider to open an issue or a discussion at the Träwelling repository. :)

**Comment by jheubuch** [comment]
The behaviour you described before is the same problem as #438

When fixed that, this issue will be fixed too.
