### ISSUE TITLE
Final train destination shown twice and at top

### ISSUE THREAD

**Issue by pief** [jheubuch/traewelling-android#48]
![Screenshot_20220916-092249_Trwelldroid](https://user-images.githubusercontent.com/2843983/190624337-b5e98224-b186-421a-8d51-93624be2bc2b.jpg)

Was reproducible twice with ICE 820 today: checking in showed the train's final destination twice, once at the bottom and incorrectly also the top.

**Comment by pief** [comment]
Here is another variant, where not the final train destination but the first one is shown as the second:

![Screenshot_20220918-160256_Trwelldroid](https://user-images.githubusercontent.com/2843983/190911006-b1959204-1c68-420b-a5e1-22ae228f5985.jpg)

**Comment by jheubuch** [comment]
I think this is an API related problem, but I indeed saw this problem myself these days.
I'll take further investigation in this one and will then fix this error or open an issue at Träwelling

**Comment by DRSchlaubi** [comment]
I looked at the request and the API sometimes returns some weird stopovers, especially if there is real time data (only if there is a delay)

**Comment by DRSchlaubi** [comment]
https://github.com/Traewelling/traewelling/issues/1126

**Comment by jheubuch** [comment]
This may be fixed now after Träwelling implemented a change
