### ISSUE TITLE
Off-by-one error when checking in to prematurely ending train

### ISSUE THREAD

**Issue by pief** [jheubuch/traewelling-android#49]
Träwelldroid may or may not have a off-by-one error when handling trains that end prematurely, i.e. where all stops beyond a certain station have been cancelled.

Seen today, 2022-09-18 with the 15:48 train from Groningen to Den Haag CS, where all stops /beyond/ Zwolle have been cancelled. The Träwelling website handles this correctly:

![Screenshot_20220918_154659](https://user-images.githubusercontent.com/2843983/190910598-e3d6d360-1ef0-4f79-b327-05cb62433200.jpg)

Whereas Träwelldroid does not allow to check-in the destination of Zwolle:

![Screenshot_20220918-154707_Trwelldroid](https://user-images.githubusercontent.com/2843983/190910626-5a932298-8400-4777-a1dc-47f56b3e303e.jpg)

This may or may not be hard to reproduce, but maybe a look at the code that generates the "destination to check-in for" list and its handling of cancelled stations is enough.

**Comment by jheubuch** [comment]
This issue duplicates #40
Thanks for your example - I'll take a look!
