### ISSUE TITLE
When Trying to add Multiple Shortcuts to Homescreen, it will only use the Name of the First Station added

### ISSUE THREAD

**Issue by ChillLP** [jheubuch/traewelling-android#66]
**Describe the bug**
See Title

**To Reproduce**
1. Go to any Station
2. Set to "Home" Station, and add to Homescreen
3. Do the Same For another Station

**Expected behavior**
Be able to add Multiple different Stations as Shortcuts when User is eg Commuting between a certain Set of stations

**Screenshots**
![Screenshot_20221024-193025_One UI Home.jpg](https://user-images.githubusercontent.com/105374102/197591066-0c666fee-e25b-4ba1-938f-60f35770fe5f.jpg).

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - OS: Android 12, One UI 4.1
 - Version: newest publicly available Version.

**Comment by DRSchlaubi** [comment]
You can only have a single home station, If you want to have other shortcuts long tap the app in the home screen. This is because träwelling only has one Home Station iirc
