### ISSUE TITLE
Spacing of different origin is strange

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#68]
![Screenshot_20221104-131949.jpg](https://user-images.githubusercontent.com/12702135/199971373-bb603924-8a27-4363-ae5a-5960f04587a3.jpg)

The screen looks a bit weird with long station names and even overlaps a bit

**Comment by DRSchlaubi** [comment]
Huh, didn't see that in later testing not sure what happened there

**Comment by jheubuch** [comment]
Should be fixed.
