### ISSUE TITLE
Caption for statistics missing operator

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#83]
For some operators (in my case Regiobus Potsdam-Mittelmark), Träwelldroid does not display the operator name in the statistics.
As the label is empty, it appears as if the next operator in the list ist displayed with two colors.![Screenshot_20221208-171845.jpg](https://user-images.githubusercontent.com/12702135/206506430-35668ae1-e344-45a8-bfb6-607f2ef7e8c3.jpg)

**Comment by jheubuch** [comment]
Got the same issue, via API a null value is delivered, I'll go and check on Träwelling
![image](https://user-images.githubusercontent.com/60344409/208457547-6180e2df-a595-4cf1-a51a-15a409cba45c.png)

**Comment by jheubuch** [comment]
When the operator value is null, Träwelling doesn't know the operator. So a default text like "Andere"/"Others" could be displayed
