### ISSUE TITLE
Station name matches search request and not actual station name

### ISSUE THREAD

**Issue by dasBunny** [jheubuch/traewelling-android#9]
When displaying the connections from a station by searching for it by name, the displayed station name is not the actual name of the station but rather the search term. 

E.g. searching for departures from Göttingen: Entering 'götting' will correctly show connections for Göttingen station, but the displayed station name is still götting. 

This may lead to confusion when there are stations with similar names and it is not clear which one is the closest match that gets its connections displayed.

**Comment by jheubuch** [comment]
Already fixed by #7
