### ISSUE TITLE
Ring lines show stops for wrong directions

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#91]
Steps to reproduce:
- select BBAB as station and filter for trams
- select a Tram 94 to Fontanestraße
- expected behaviour: only stops in direction Fontanestraße (Anhaltstraße, Plantagenstraße, Fontanestraße) are shown (as is the case on beta.traewelling.de)
- actual behaviour: all stops in the opposite direction are shown, as the line is a ring line and stops in BBAB twice. I expect the stops until the second one to not show up

**Comment by jheubuch** [comment]
Apply time based filters onto the displayed stations

**Comment by jheubuch** [comment]
Is this still a problem?

**Comment by jeriox** [comment]
yes, I encountered the problem a few times in the last weeks. It doesn't seem to happen all the times, I'll try to pinpoint under which circumstances it occurs

**Comment by jeriox** [comment]
![Screenshot_2023-06-23-09-17-36-34_6eaab5f62e0cb9204f88373d41d52439.jpg](https://github.com/Traewelldroid/traewelldroid/assets/12702135/9e8375c6-9753-477b-b069-3535fb0b98d9)

yep, just happened again. The first stop in Plantagenstraße (almost 50mins earlier) is used, but the departure that i clicked on was the 9:26 in the other direction
