### ISSUE TITLE
Use stations on profile view as entry point for departures

### ISSUE THREAD

**Issue by jeriox** [jheubuch/traewelling-android#92]
It would be great to tap on stations in the profile view and be redirected to the departures in the same way as it works on the dashboard

**Comment by DRSchlaubi** [comment]
Actually don't know why this isn't happening already as the CheckIn Card, which has that functionality, is used both on dashboard and profile

**Comment by jheubuch** [comment]
> Actually don't know why this isn't happening already as the CheckIn Card, which has that functionality, is used both on dashboard and profile

It's because at the moment there is no action from UserFragment to SearchConnectionFragment defined. This action has to be created and passed either to the CheckInCard itself or the CheckInAdapter
