### ISSUE TITLE
Coloring actions

### ISSUE THREAD

**Issue by dnil-io** [jheubuch/traewelling-android#96]
**User story**

As a first time user I want the used colors among other things to guide me which actions I can take so that I have an easier time figuring out the apps functionality.

**Acceptance criteria**
  - Accent color is choosen (light blue?)
  - Some clickable items use accent color or other hints about their behaviour
    - User names in card view
  - Non-clickable items don't use accent color
    - User stats on "Profil"-page
    - User name on "Profil"-page
    - Stop symbols "The circles next to station names"
    - Headings ("Wo bist du?")
   - Clues used should be consistent all over the app (If some clickable icons are colored, they should be colored everywhere; If some clickable time strings are colored, all time strings should be colored) 
 
**Additional context**
 Clickable elements need sufficient clues to be identified as such. On the other hand, non clickable elements should not share the same clues. Non-clickable text should never be blue. ([Jakob's law](https://lawsofux.com/jakobs-law/))

[Blog article ](https://ux4sight.com/blog/ux-training-how-to-optimize-the-use-of-accent-colors) about accent colors.

**Comment by jheubuch** [comment]
This is fixed by #155
